Don't swallow helpful errors
Instead of the helpful

```
NoMethodError: undefined method `GEOSversion' for Geos::FFIGeos:Module
```

that would point me to a missing library, I was getting

```
LoadError: Couldn't load the GEOS CAPI library
```